### PR TITLE
Adding GTK+3 support

### PR DESCRIPTION
**Pull request by jorgicio**
Hi!
I took the time to fork and adding support for GTK+ 3.0, for anyone want to try.

I appreciate your response and approval.
Thanks!

### CODE REVIEW

**Comment by pantera31752** [comment]
thanks. I myself would like to add support for GTK + 3.0 is simply not enough time

**Comment by pantera31752** [comment]
how can you be contacted? I have ideas about creating a fork Gentoo Linux

**Comment by jorgicio** [comment]
Hi! Thanks for your response.
if you want it, just check my website: http:/www.jorgicio.net

Also, I messed up some things, and just fix it. Please, accept this new pull request :D

**Comment by pantera31752** [comment]
Can you give your email?

**Comment by jorgicio** [comment]
Sure: thirteenth [dot] step [dot] 1707 [at] gmail [dot] com
P.S.: fixed another conflict and did the commit :D

**Comment by pantera31752** [comment]
All right

**Comment by jorgicio** [comment]
Thanks, and sorry again for the inconveniences. As I messed up some things, I have to fix and you'll get noticed for the commits :)

**Comment by jorgicio** [comment]
Yet more hehehe sorry again! I try to do the best!

**Pull request merged**
